### ISSUE TITLE
Fully implement f64x4 and f32x8

### ISSUE THREAD

**Issue by liebharc** [huonw/simd#17]
Is there any reason _f64x4_ and _f32x8_ don't implement the traits _Mul_, _Div_, ... , and custom traits for _addsub_ and other operations from the avx instruction set?

I did a few changes on a fork (https://github.com/liebharc/simd) and it appears that just a little code is missing to complete the avx register types for floating point numbers. Also the performance in my complex multiplication benchmark is where I would expect it to be with the _f64x4_ type. I can of course go on to implement that and open a pull request, but before I do that I would like to understand if there is a reason why this isn't there yet.

**Comment by rekka** [comment]
Coincidentally, I am also looking into this since this weekend. It'd be great to have all the implementations the integer/bool types as well. This is a bit complicated by the fact that AVX does not have a support for arithmetic and logic operations on 256-bit integers, this comes with AVX2. So functions like `bool64ix4::any` and `bool64ix4::all` should have different implementations depending on the availability of AVX2 feature. 

**Edit**: I take it back, the compiler gracefully falls back to AVX 128-bit integer operations when AVX2 is not enabled. And AVX has `mm256_test*_si256` for an efficient implementation of `bool64ix4::any` and `bool64ix4::all`, etc., functions. Everything seems to work fine as far as I can see. I am almost done implementing this on top of https://github.com/liebharc/simd so I will probably open a pull request when I am finished: https://github.com/rekka/simd/tree/avx
